### PR TITLE
Litle error

### PR DESCRIPTION
**Pull request by TonyDiana**

### CODE REVIEW

**Comment by mammo0** [comment]
Thank you :)

**Comment by TonyDiana** [comment]
> Thank you :)

Method should have "self" as first argument in 
    @classproperty
    def foo(cls):
        return cls.__var

¿Solution?
Tx

**Comment by mammo0** [comment]
You can ignore this warning.

Pylint does not know the `@classproperty` decorator. So it thinks it's a normal method and expects the `self` argument as the first one of the method.
On the otherside Pylint knows the `@classmethod` property and allows for this decorator another name for the first argument.

**Comment by TonyDiana** [comment]
Yes, I know, the problem is that it drives me crazy, hehehe, I have seen that, if I use self, instead of cls, it does not give an error and everything works, which is not what I would like, but it is a solution (I am dyslexic and it helps me to use Pylint together with Flake8). By the way, if you want to see the project where I use your product, the link is this: (https://tonydiana.gitlab.io/zeus/docs/html/src/docstrings/python/terceros/scp/index.html), I embedded the code within the project so as not to have dependencies that the end user has to handle, and I had to modify the "__init__.py", as follows:

from .classproperty_decorator import _classproperty
from .classproperty_meta import _ClasepropertyMeta

Please tell me how you want to be mentioned in the acknowledgments section

https://tonydiana.github.io/Olimpo/docs/html/src/presentacion/agradecimientos.html

Very kind.

**Comment by mammo0** [comment]
You can name the first as you like. By convention it is `self`. So your program works also if it's got another name...

May you tell Pylint to ignore this error at the specific line with:
```python
@classproperty
def foo(cls, args):  #pylint disable=no-self-argument
    pass
```

> Please tell me how you want to be mentioned in the acknowledgments section
First thank you, that you want to list me there. This needn't be something special. I think a link to my repository will be more than sufficient.

**Comment by TonyDiana** [comment]
It is from `` #pylint disable = no-self-argument`` I did not know it, very good.

The thing is, I use VSC and it doesn't work in that context, but thanks.

It will be included with a link, and its original documentation has been respected.

Thanks.

**Pull request merged**
