### PR TITLE
Update classproperty_decorator.py

### PR DESCRIPTION
**Pull request by TonyDiana**
Greetings.
This is a crude way of getting their attention. I am trying to get sphinx to document the decorated methods like:

     @classproperty
     def border (cls) -> int:
         "" "Returns the border value between with and without mirror." ""
         return 200

With this barbarity I need to do

     @classproperty
    @docu
     def border (cls) -> int:
         "" "Returns the border value between with and without mirror." ""
         return 200

But my knowledge of metaclasses prevents me from integrating both.

I know I'm close, but I can't, I don't know if you would have a problem incorporating something to solve the problem.

Respectfully yours:

### CODE REVIEW

**Comment by mammo0** [comment]
Hello,
I'm sorry, but I haven't used Sphinx yet. So I do not know how it works exactly...

Maybe you can explain why the additional `@docum` decorator is needed in your case.

**Comment by TonyDiana** [comment]
Greetings, any docstrings docstrings ignore the docstrings of the functions decorated with @classproperty, that's why the second decorator is necessary, or modify your script so that it returns the wrapper

https://stackoverflow.com/questions/43544954/why-does-sphinx-autodoc-output-a-decorators-docstring-when-there-are-two-decora

**Comment by mammo0** [comment]
Ah, ok now I got your point.

I've found this: https://stackoverflow.com/questions/6394511/python-functools-wraps-equivalent-for-classes

Will have a look at it tomorrow if I can implement this.

**Comment by TonyDiana** [comment]
Tx

**Comment by mammo0** [comment]
Please check out my change in the 'fix_decorator_special_vars' branch:

https://github.com/mammo0/py-simple-classproperty/blob/fix_decorator_special_vars/simple_classproperty/classproperty_decorator.py

Does this work for you?

**Comment by TonyDiana** [comment]
:( not work

Captura de pantalla de 2021-07-01 16-29-16
Captura de pantalla de 2021-07-01 16-31-12

**Comment by mammo0** [comment]
Hello,

I've looked at the problem in more detail. But I think this is something that can't be solved...

Have a look at: https://stackoverflow.com/questions/38118264/how-can-i-retrieve-the-docstring-for-a-property-of-a-python-class-instance
There it says for docstrings to work the properties must be accessed through the class. But since I'm implementing a class property, the property is already accessed by the class.

Look at this example:
```python
class Foo(metaclass=ClasspropertyMeta):
    @classproperty
    def val(cls):
        return 1
```
From "outside" this class will look like this:
```python
class Foo():
    val = 1
```

Then you have this case: https://stackoverflow.com/a/61204074
You can't access the docstring, because you get back the return value of your property-function and not the property-function itself.

I tried also your suggestion from this PR, but it doesn't work for me at all. Can you give me a working example?

**Comment by TonyDiana** [comment]
this work, https://docs.astropy.org/en/stable/api/astropy.utils.decorators.classproperty.html
I have been analyzing the code, and it works, but it is very computationally expensive and complex and uses many auxiliary libraries that, for that matter, are excessive but for the context of the astropy they make sense, and the additional cost does not matter.

**Comment by TonyDiana** [comment]
https://python-reference.readthedocs.io/en/latest/docs/functions/property.html

I've been playing with this, but I haven't been able to get it to work either

https://stackoverflow.com/questions/43544954/why-does-sphinx-autodoc-output-a-decorators-docstring-when-there-are-two-decora

**Comment by mammo0** [comment]
Well, if the implementation of https://docs.astropy.org/en/stable/_modules/astropy/utils/decorators.html#classproperty works for you, than you may just use this one.

I've set up a simple project with Sphinx and the above implementation of the classproperty. But in the generated documentation this classproperty is not printed at all. What Sphinx configuration do you use?

**Comment by TonyDiana** [comment]
# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys

sys.path.insert(0, os.path.abspath('../../../Atica/fotest/src'))

# Burlarse de módulos
# autodoc_mock_imports = ['terceros.tinydb']

# -- Project information -----------------------------------------------------
project = 'Fotoestación'
copyright = '2020-ss, Tony Diana'
author = 'Tony Diana'

# The short X.Y version
from zeus.version import VERSION
version = VERSION
# The full version, including alpha/beta/rc tags
release = ''


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.intersphinx',
    'sphinx.ext.ifconfig',
    'sphinx.ext.githubpages',
    'sphinx.ext.todo',
    'sphinx.ext.imgmath',
    'recommonmark',
    'myst_parser',
    # --- 'sphinx.ext.viewcode',
]

#   viewcode_enable_epub = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
source_suffix = {
    '.rst': 'restructuredtext',
    '.md': 'markdown',
}
# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'es'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['*.txt']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = None


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#

# html_theme = 'furo'

html_theme = 'sphinx_rtd_theme'
html_theme_options = {
    'canonical_url': '',
    'analytics_id': '',
    'logo_only': False,
    'display_version': True,
    'prev_next_buttons_location': 'bottom',
    'style_external_links': True,

    # Toc options
    'collapse_navigation': True,
    'sticky_navigation': True,
    'navigation_depth': -1,
    'includehidden': True,
    'titles_only': False
}
autodoc_member_order = 'bysource'


# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
html_show_sphinx = False
# If true, links to the reST sources are added to the pages.
html_show_sourcelink = False

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = 'rec/ico.png'

# The name of an image file (relative to this directory) to use as a favicon of
# the docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = 'rec/favicon.ico'

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'Fotoestación'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
# latex_documents = [
#    (master_doc, 'Exposimetro.tex', 'Exposimetro: Documentación',
#     'Tony Diana', 'manual'),
# ]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
# man_pages = [
#    (master_doc, 'exposimetro', 'Exposimetro: Documentación',
#     [author], 1)
# ]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
# texinfo_documents = [
#    (master_doc, 'Exposímetro', 'Foto Estación',
#     author, 'Tony Diana', 'Gestión integral fotográfica',
#     'Fotografía'),
# ]


# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']


# -- Extension configuration -------------------------------------------------
# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

**Comment by mammo0** [comment]
Sorry for the late answer, but I was quite busy the last few days...

I've tried your Sphinx config but can't reproduce that the classproperty of Astropy works with Sphinx. If I decorate a function with their classproperty this function is simply not printed in the generated documentation. No output at all. Did you do something more? Any additional config or plugin/extension?

**Comment by TonyDiana** [comment]
No, nothing special, I did a simple test to try to learn from the code and implement it. As I mentioned, Astropy consumes quite a few resources and forces the use of many inherited classes that inherit from inherited classes that previously inherited ... too many for my liking. Obvious in its cool context, but it's not what I mean.

It seems to me that it works thanks to this:

    def __new __ (cls, fget = None, doc = None, lazy = False):
        if fget is None:
            # Being used as a decorator - return a wrapper that implements
            # decorator syntax
            def wrapper (func):
                return cls (func, lazy = lazy)

            return wrapper

        return super () .__ new __ (cls)

Here is wrapper

On the other hand, many of the solutions for the same problem (https://stackoverflow.com/questions/5189699/how-to-make-a-class-property) implement a decorator class and function, which is not the case of yours, since it is the only one in which the class that contains the decorated method must belong to `` ClasepropertyMeta``, interesting, but I really, I can't get to that level.

In any case, I really appreciate your attention, it is a detail on your part.

**Comment by TonyDiana** [comment]
I have come this far:

    from functools import wraps

    def classproperty (func):
       @wraps (func)
       def container (func):
           if not isinstance (func, (classmethod, staticmethod)):
               func = classmethod (func)
           return func
       return container

The comments work for me but not the decorator, it produces an error

**Comment by mammo0** [comment]
> It seems to me that it works thanks to this:
> ```
> def __new __ (cls, fget = None, doc = None, lazy = False):
>     if fget is None:
>         # Being used as a decorator - return a wrapper that implements
>         # decorator syntax
>         def wrapper (func):
>             return cls (func, lazy = lazy)
> 
>         return wrapper
> 
>     return super () .__ new __ (cls)
> ```

I've tried it not with my implementation, but only with the source code from Astropy. Sphinx produces the same output for their classproperty implementation as for mine. Namely nothing for the classproperty function...

> On the other hand, many of the solutions for the same problem (https://stackoverflow.com/questions/5189699/how-to-make-a-class-property) implement a decorator class and function, which is not the case of yours, since it is the only one in which the class that contains the decorated method must belong to ClasepropertyMeta, interesting, but I really, I can't get to that level.

The `ClasepropertyMeta` class is only really necessary if you want to implement a setter and/or deleter for your property. If you want only the getter function, then the decorator is enough. But I recommend to use the metaclass, because it prevents the developer from accidentally  overwriting the classproperty with any other value/function/whatever.

But back to the main problem of this PR. I think for Sphinx the main problem is that it can't get the docstring of the classproperty function. But I don't think that is possible at all, because if you want to access the classproperty of a class, e.g.

```python
class Foo(metaclass=ClasspropertyMeta):
    @classproperty
    def val(cls):
        return "bar"
```

then you directly get the value. If you do `Foo.val` you get `'bar'` and not a `classproperty` object. So for for calling `Foo.val.__doc__` you get `'bar'.__doc__` which is the docstring of a string and not of the classproperty function.

I don't see a possibility for detecting if one wants to access the value of the classproperty during program execution or the classproperty object itself while generating the documentation with Sphinx.

**Comment by TonyDiana** [comment]
Yes, I am very frustrated with this too.
I developed this:

    # --- Python standard library
    from functools import wraps
    
    
    # --- One thing that doesn't work
    #
    def docum (func):
        @wraps (func)
        def wrapper (* args, ** kwargs):
            return func (* args, ** kwargs)
        return wrapper
    
    
    # --- Decorator class
    #
    class ClassPropertyObject (object):
    
        def __init __ (self, fget, fset = None):
            if not isinstance (fget, (classmethod, staticmethod)):
                self.fget = classmethod (fget)
    
            else:
                self.fget = fget
    
            self.fset = fset
            self .__ doc__ = fget .__ doc__
    
        #
        def __call __ (self, * args, ** kwargs):
            self.fget (* args, ** kwargs)
    
        #
        def __get __ (self, obj, klass = None):
            if klass is None:
                klass = type (obj)
            return self.fget .__ get __ (obj, klass) ()
    
        #
        def __set __ (self, obj, value):
            if not self.fset:
                raise AttributeError ("Attribute does not exist")
            type_ = type (obj)
            return self.fset .__ get __ (obj, type _) (value)
    
        #
        def setter (self, func):
            if not isinstance (func, (classmethod, staticmethod)):
                func = classmethod (func)
            self.fset = func
            return self
    
    
    #
    def classproperty (func):
        "" "Decorator to generate class property." ""
        return ClassPropertyObject (func)
    
But I can't make it work either. If the __doc__ can be read using a double decorator (1st @classproperty and then @docum, so that it first documents and then does its job), it doesn't work, it doesn't return the required value:

    def tuplefactors (cls) -> list:
        "" "Returns the factor dictionary converted to tuple / tuples." ""
        return tuple (cls.FACTOR_CoC.items ())

As if I had not put a return

**Comment by mammo0** [comment]
I think you ran exactly into the issue that I have described with my last example. From where should the program "know" if it should deliver the docstring or the value of the classproperty. I think this can't be detected at runtime.

And I also don't think that any additional decorator will help here...

**Comment by TonyDiana** [comment]
Yes, I already threw in the towel, I give up

**Comment by mammo0** [comment]
Ok, then I'm closing this now. If you find a working solution, feel free to reopen this PR again.

Thank you.

**Pull request closed without merging**
